baseURL = "https://kdbed.github.io/"
languageCode = "en-us"
title = "Owlglass"
theme = "cortex"
publishDir = "docs"
[params]
email = "kdbednar8@gmail.com"
footer = "Icon by Freepik. Built with ♥ with Org-mode and Hugo."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
      anchorLineNos = false
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      hl_inline = false
      lineAnchors = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = true
      style = "monokai"
      tabWidth = 4
