:PROPERTIES:
:ID:       811284ca-b465-4bc4-9958-220a2a4d0f2f
:END:
#+title: Conditions of Causation
#+hugo_base_dir:../


* Conditions of Causality
There are four conditions of causality: logical time ordering, correlation, mechanism, and nonspuriousness. Logical time ordering refers to the idea that one variable needs to precede another variable in time for the first variable to influence the second variable. For example, throughout the world, people are protesting their governments. In some countries, governments respond with the metaphorical yawn. However, in other countries, the governments may respond with repressive tactics. The question is do the protest precede the government response? On its face, the answer is yes because why would the government respond to silence?

The second condition of causality is correlation. As we explored above, correlation is a connection between two variables. Correlation is a prerequisite to establishing a causal relationship because if two variables do not move together, then it is difficult to suggest that one influences the other. Maintaining our example of public protest and government response, we often see that when people protest, the government pays attention. This is due to mainstream media coverage and social media activity of the protest. Since governments typically have responsibility for maintaining peace and security, anytime there are activities that may disrupt peace, the government will likely pay attention to what the media is covering and decide whether to respond.

Our third condition of causality is mechanism. A causal mechanism is an explanation for how one variable influences the other. Explanations can vary from relatively straightforward to exhaustively complex. There is utility in employing both types of explanations to describe the influence of one variable on the next variable. The reason is it may be straightforward to some while the government responds to protesters. However, underlying this interaction, there may be other actors, decisions, and actions that may shape engagement between the government and protesters. For example, the Arab Spring starting in 2010 provides a contemporary example where people throughout countries in the Middle East publicly protested for changes in their political leadership and government systems. How did these protesters come together? Some researchers point to social media, like Facebook and Twitter, which helped people collectively organize their protesting efforts. Thus, we have a mechanism that shows how protest formed, and how that initiated reaction from governments.

The final condition of causality is non-spuriousness. Non-spuriousness means that another variable is not having an influence. With our example of protest and government response, we must be careful to consider that other factors may influence this relationship. What else could influence a government's response to a protest within its country? A government may be hesitant to respond with lethal force if it knows it's being observed by an international media. An international media outlet serves as a third-party observer to the activities within a country. As the media records through video and first-hand accounts, they can begin to share that information with the rest of the world. A government that uses lethal weapons on people who are peacefully protesting could result in an outcry from the international community. Thus, are protests the only thing that is influencing the government's response? Or is there a spurious factor, such as the international media outlet, that having the government question how it should respond?

As you can see, from a running example of public protest and government action, establishing a causal relationship between two variables is difficult. The difficulty doesn't mean we don't work through these four conditions, both using reason and evidence, rather it represents a rigorous way to determine a causal relationship.

from [[https://socialsci.libretexts.org/Bookshelves/Political_Science_and_Civics/Book%3A_Introduction_to_Political_Science_Research_Methods_(Franco_et_al.)/04%3A_Theories_Hypotheses_Variables_and_Units/4.01%3A_Correlation_and_Causation][libretexts]]
