:PROPERTIES:
:ID:       f3de8097-4a5c-46bb-8915-11f0e481d0a1
:END:
#+title: Inverse-Square Potential in Quantum Mechanics
#+filetags: :quantumMechanics:
#+hugo_base_dir:../


* The inverse-square potential in quantum mechanics
** Intro
The inverse-square potential in quantum mechanics is connected to phenomena like electron capture by neutral polar molecules, the Efimov effect in a system of three identical bosons, the transition between asymptotically-free and conformal phases in QCD-like theories as a function of the ratio of the number of quark flavors to colors, and the AdS/CFT correspondence. The attractive $$ 1/x^2 $$ potential is interesting because it naturally calls upon the framework of the [[id:8f2f3db9-b92a-4ea4-871b-c82c8abc617e][Renormalization Group]]. This approach will be seen to mirror the modern treatment of quantum effective field theories whereby one demans that long-distance observables remain insensitive to the adjustment of fine details at short distances.
** Pure Inverse-Square Potential
Consider the potential
$$
V(x) = \begin{cases}
\infty & \text{if } x \leq 0 \\
\frac{\alpha}{x^2} & \text{if } x > 0
\end{cases}
$$
for $$ -1/4 < \alpha < 0$$. Work in units with $$ \hbar = 1$$ so energy is the reciprocal of time, $$ \hbar^2/2m = 1 $$ so that energy is also the reciprocal of length-squared. Thus time and length-squared have equivalent dimensions. $$\alpha$$ is dimensionless.





** Ref
Taken directly from: https://arxiv.org/pdf/1707.04388
