:PROPERTIES:
:ID:       76082ed2-6ddc-4d1c-9520-be497764fe61
:END:
#+title: Quotes

* Quotes
** Quote 1 - [[id:29d4bee9-4e25-44fa-a14c-3377f1d7d50b][Marx]]
You would be wrong if you thought that I love books. I am a machine condemned to devour them in order to vomit them up in a new form, like manure on the soil of history.

— Marx in a letter to his daughter Laura, 1868

** Quote 2
"Meet these two here," the man said.  "Ask them if they've got a Mississippi credit card."

"Oh, I know that one," Ruthie explaimed cheerfully.  "That's four feet of garden hose to siphon gas, am I right?" She looked at Willie slyly, then turned to Liberty and showed her teeth.

- _Breaking and Entering_ , Joy Williams, p17

** Quote 3
"Something is profoundly wrong with the way we live today.  For thirty years we have made a virtue out of the pursuit of material self-interest: indeed, this very pursuit now constitutes whatever remains of our sense of collective purpose.  We know what things cost but have no idea what they are worth.  We no longer ask of a judicial ruling or a legislative act: is it good? Is it fair? Is it just? Is it right? Will it help bring about a better society or a better world? These used to be =the= political questions, even if they invited no easy answers.  We must learn once again to pose them."

- _Ill Fares the Land_ - Tony Judt
** Quote 4
"To see what is in front of one's nose needs a constant struggle."

- George Orwell
