:PROPERTIES:
:ID:       76082ed2-6ddc-4d1c-9520-be497764fe61
:END:
#+title: Quotes and Notes
#+hugo_base_dir:../

* Quotes and Notes
** 1 - [[id:29d4bee9-4e25-44fa-a14c-3377f1d7d50b][Marx]]
You would be wrong if you thought that I love books. I am a machine condemned to devour them in order to vomit them up in a new form, like manure on the soil of history.

— Marx in a letter to his daughter Laura, 1868

** 2
"Meet these two here," the man said.  "Ask them if they've got a Mississippi credit card."

"Oh, I know that one," Ruthie explaimed cheerfully.  "That's four feet of garden hose to siphon gas, am I right?" She looked at Willie slyly, then turned to Liberty and showed her teeth.

- _Breaking and Entering_ , Joy Williams, p17

** 3
"Something is profoundly wrong with the way we live today.  For thirty years we have made a virtue out of the pursuit of material self-interest: indeed, this very pursuit now constitutes whatever remains of our sense of collective purpose.  We know what things cost but have no idea what they are worth.  We no longer ask of a judicial ruling or a legislative act: is it good? Is it fair? Is it just? Is it right? Will it help bring about a better society or a better world? These used to be =the= political questions, even if they invited no easy answers.  We must learn once again to pose them."

"Why do we experience such difficulty even *imagining* a different sort of society? Why is it beyond us to conceive of a different set of arrangements to our common advantage? Are we doomed indefinitely to lurch between a dysfunctional 'free market' and the much-advertised horrors of 'socialism'?

Our disability is *discursive*: we simply do not know how to talk about these things any more.  For the last thirty years, when asking ourselves whether we support a policy, a proposal or an initiative, we have restricted ourselves to issues of profit and loss--economic questions in the narrowest sense.  But this is not an instinctive condition: it is an acquired taste."

- _Ill Fares the Land_ - Tony Judt
** 4
"To see what is in front of one's nose needs a constant struggle."

- George Orwell
** 5
"He's that lazy he won't get up off the ground sometimes when he stumbles." - Dude Lester of Jeeter, _Tobacco Road_, Caldwell

"Them two dirty holes in her face don't do a man no good to look at." Jester of Bessie
** 6
"Eppur si muove" -- and yet it moves; supposedly muttered by Galileo in 1633; can mean that although someone who possesses true knowledge is forced to renounce it, it does not stop it from being true. The story can illustrate the exact opposite: a deeper symbolic truth can be illustrated by something untrue (true designation of Galileo's subjective position even though it's likely false); reality of fiction (Zizek)
** 7
The premise of discursive materialism is to conceive language itself as a mode of production and to apply to it Marx's logic of commodity fetishism.
** 8
In a Hegelian way, the problem (ie reporting trauma) is here part of the solution: the very deficiencies of the traumatized subject's report on the facts bear witness to the truthfulness of his report, since they signal that the reported content has contaminated the very form in which it is reported. - Zizek
** 9
Chesterton: "Tolerance is the virtue of the man without convictions."

Paul Claudel: "Mais la tolérance? Il y a des maisons pour ça!"
** 10
