:PROPERTIES:
:ID:       76082ed2-6ddc-4d1c-9520-be497764fe61
:END:
#+title: Quotes and Notes
#+hugo_base_dir:../

* Quotes and Notes
** 1 - [[id:29d4bee9-4e25-44fa-a14c-3377f1d7d50b][Marx]]
You would be wrong if you thought that I love books. I am a machine condemned to devour them in order to vomit them up in a new form, like manure on the soil of history.

— Marx in a letter to his daughter Laura, 1868

** 2
"Meet these two here," the man said.  "Ask them if they've got a Mississippi credit card."

"Oh, I know that one," Ruthie explaimed cheerfully.  "That's four feet of garden hose to siphon gas, am I right?" She looked at Willie slyly, then turned to Liberty and showed her teeth.

- _Breaking and Entering_ , Joy Williams, p17

** 3
"Something is profoundly wrong with the way we live today.  For thirty years we have made a virtue out of the pursuit of material self-interest: indeed, this very pursuit now constitutes whatever remains of our sense of collective purpose.  We know what things cost but have no idea what they are worth.  We no longer ask of a judicial ruling or a legislative act: is it good? Is it fair? Is it just? Is it right? Will it help bring about a better society or a better world? These used to be =the= political questions, even if they invited no easy answers.  We must learn once again to pose them."

"Why do we experience such difficulty even *imagining* a different sort of society? Why is it beyond us to conceive of a different set of arrangements to our common advantage? Are we doomed indefinitely to lurch between a dysfunctional 'free market' and the much-advertised horrors of 'socialism'?

Our disability is *discursive*: we simply do not know how to talk about these things any more.  For the last thirty years, when asking ourselves whether we support a policy, a proposal or an initiative, we have restricted ourselves to issues of profit and loss--economic questions in the narrowest sense.  But this is not an instinctive condition: it is an acquired taste."

- _Ill Fares the Land_ - Tony Judt
** 4
"To see what is in front of one's nose needs a constant struggle."

- George Orwell
** 5
"He's that lazy he won't get up off the ground sometimes when he stumbles." - Dude Lester of Jeeter, _Tobacco Road_, Caldwell

"Them two dirty holes in her face don't do a man no good to look at." Jester of Bessie
** 6
"Eppur si muove" -- and yet it moves; supposedly muttered by Galileo in 1633; can mean that although someone who possesses true knowledge is forced to renounce it, it does not stop it from being true. The story can illustrate the exact opposite: a deeper symbolic truth can be illustrated by something untrue (true designation of Galileo's subjective position even though it's likely false); reality of fiction (Zizek)
** 7
The premise of discursive materialism is to conceive language itself as a mode of production and to apply to it Marx's logic of commodity fetishism.
** 8
In a Hegelian way, the problem (ie reporting trauma) is here part of the solution: the very deficiencies of the traumatized subject's report on the facts bear witness to the truthfulness of his report, since they signal that the reported content has contaminated the very form in which it is reported. - Zizek
** 9
Chesterton: "Tolerance is the virtue of the man without convictions."

Paul Claudel: "Mais la tolérance? Il y a des maisons pour ça!"
** 10
Plato in Statesman: divisions (of genus into species) should be made at the proper joints. Eg, it is a mistake to divide the genus of all human beings into Greeks and 'barbarians' -- not a proper form becaause it does not designate a positively defined group (species), but merely all persons who are not Greek. The positivity of the term 'barbarian' thus conceals the fact that it serves as the container for all those who do not fit the form 'Greek'.  Hegel's (and Lacan's) hypothesis is that this holds for all divisions of a genus into species: every genus, in order to be fully divided into species, has to include such a negative pseudo-species, a 'part of no part' of the genus, all those who belong to the genus but are not covered by one of the species.  This 'contradiction' between a genus and its species, embodied in an excessive group whose consistency is purely negative, is what sets a dialectical process in motion.
** 11
Trends inequality: postindustrial, information age in which semi-skilled workers are no longer in demand; consequent increase in value of women's labor, dual income model in which peers are more likely to marry; thus affect marriage and divorce rates and family as 'incubator'; increasing inequality of opportunity can lead to inequality of outcome
** 12
One cannot really understand the scientific worldview unless one assumes that the intelligibility of the world, as described by the laws that science has uncovered, is itself part of the deepest explanation of why things are as they are. -- T.Nagel
** 13
Gossip theory of cognitive revolution; able to gossip (maintain trust, etc) on 150 folks; more than that requires myth-making; relation between individual myth (eg Hero 1000 Faces) and societal myth (statemaking);
** 14
The problem this raises, of course, is-how is this possible? How does one mix things that don't appear to mix? What allows Marx to construct theories-for this is what I am claiming-that are at the same time scientific, critical, visionary, and revolutionary? For the tale of two cities presented above, this translates as-what allows Marx to discover communism inside capitalism, and how does what he finds constitute both a criticism of capitalism and the basis of a strategy to overturn it? At the core of every science is a search for relations, especially relations that are not immediately obvious, and in studying capitalism Marx uncovers relations between what is, what could be, what shouldn't be, and what can be done about it all. He finds all this, first of all, because it is there, but what permits him to find it-while most students of capitalism only come up with the appearances (mislabeled as "facts")-is his dialectical method. It is dialectics, and Marx's dialectics in particular, that not only allows but requires him to knit together what most others consign to separate mental compartments. - _Dance of the Dialectic_, Ollman
** 15
Four causes of potential crises: i) human pressures on Earth's ecosystem and climate; ii) rising population; iii) extreme poverty; iv) cynicism, defeatism, outdated institutions
** 16
Coal liquefaction is a process of converting coal into liquid hydrocarbons: liquid fuels and petrochemicals. This process is often known as "coal to X" or "carbon to X", where X can be many different hydrocarbon-based products. However, the most common process chain is "coal to liquid fuels" (CTL).  Coal liquefactions originally was developed at the beginning of the 20th century.[2] The best-known CTL process is Fischer–Tropsch synthesis (FT), named after the inventors Franz Fischer and Hans Tropsch from the Kaiser Wilhelm Institute in the 1920s.[3] The FT synthesis is the basis for indirect coal liquefaction (ICL) technology. Friedrich Bergius, also a German chemist, invented direct coal liquefaction (DCL) as a way to convert lignite into synthetic oil in 1913.  ---- 1908-1914 Haber+Bosch process of synthesizing nitrogen-based chemical fertilizers (atmospheric N_2 --> N-based compounds)
