:PROPERTIES:
:ID:       304b84f8-6a1d-4535-9a76-c5480a606de8
:END:
#+title: Trump - Policies and Actions
#+hugo_base_dir:../
#+filetags: :politics:trump:

An analysis of the coherence -- or lack thereof -- of Trump's policies and [[id:bba56906-b7ec-43f4-8ce5-f372017f4339][politics]] , along with general remarks on what he did while in office.

* Changes in American Policy
Many Americans will remember President Donald Trump's presidency as a four-yearlong storm of tweets, rallies and on-air rants that ended in a mob riot and historic second impeachment. But there was more to the Trump presidency than attention-hogging political drama and conflict; often unnoticed, Trump and his administration actually did succeed in changing some of the ways Washington works.

** Obamacare -- accidentally bolstered
Trump came into office vowing to repeal Obamacare and even took the law to court when that failed in Congress. But his most significant imprint on the Affordable Care Act was an accidental boost that happened when he stumbled into pouring billions of extra federal dollars into subsidizing Americans' coverage.

House Republicans had tried for years to cut off subsidies that helped low-income Obamacare enrollees with the co-pays, co-insurance and deductibles that come with their health plans. In 2017, Trump finally did it through administrative means after the GOP effort to replace the law fell apart, and he immediately drew intense outcry from Democrats and policy experts who called the move sabotage.

The health exchanges didn't collapse, as Trump had hoped. Instead, health plans and states quickly figured out a way to claw back the federal dollars they lost: they built the costs of the subsidies into premiums for Obamacare's benchmark "silver" policies. This meant that premiums for these "silver" plans spiked and as a result, the premium subsidies the government had to pay for low-income enrollees vastly increased. The concept, known as "silver-loading," ([[https://www.brookings.edu/essay/the-case-for-replacing-silver-loading/][Brookings]] , [[https://news.bloomberglaw.com/health-law-and-business/with-obamacare-plans-cost-of-silver-is-seen-as-too-cheap][Bloomberg]]) grew government subsidizing of the exchanges by upwards of $20 billion per year.

While Trump's moves made Obamacare plans increasingly unaffordable for the unsubsidized, Democrats quickly tamped down their criticisms since it accomplished their goal of significantly boosting funding for Obamacare. The incoming Biden administration isn't likely to reverse course.
** Strategy -- refocused national security on great power competition
Trump administration's [[https://dod.defense.gov/Portals/1/Documents/pubs/2018-National-Defense-Strategy-Summary.pdf`:w`][National Defense Strategy]] stands out as one of the most important defense policy shifts of the last generation, reorienting the American military to confront rising and increasingly aggressive powers Russia and China.

The move: The 2018 strategy rewired the Defense Department's vast bureaucracy away from a focus on fighting insurgents and terrorists in the Middle East toward a long-term strategic competition with China and Russia. As a result, the military is changing how it trains personnel, which technologies it buys, and the geographic areas of the world where it prioritizes its forces.

The impact: Already it has led to a reordering of the Pentagon budget and new investments supported by a bipartisan majority in Congress, including billions of dollars to beef up the U.S. military presence in the Asia-Pacific.

The upshot: Despite differences in tone and rhetoric, this is a refocusing of the United States' military posture that is expected to continue in the Biden administration.
** Coronavirus -- no workplace guidance
Arguably the most consequential decision Trump made involving American workers was something it chose not to do: It declined to implement a so-called 'emergency temporary standard' when the coronavirus pandemic hit. Such a standard, issued when the Occupational Safety and Health Administration determines workers are in 'grave danger,' would have established immediate and mandatory workplace safety rules employers must follow to protect employees from exposure.

The move: Despite pressure from Democrats, unions and worker advocates, OSHA refused to set rules for worker safety during the pandemic. Republicans defended the decision by saying the burden on companies struggling to stay afloat amid the recession would be too great. In the absence of a standard, employers have only had to comply with a mix of optional guidelines, able to pick and choose what precautions they take.

The impact: The agency's backseat approach to workplace safety means Americans still face a dangerously unpredictable range of safety conditions when they show up to work. Though OSHA has cited some companies for coronavirus-related transgressions, many large corporations received meager fines even in cases where workers died from Covid-19. Democrats have attempted to include language mandating an emergency temporary standard in future rounds of pandemic aid, but their efforts have been unsuccessful.

The upshot: One of the first things a Biden administration will likely move to do is instruct OSHA to step up worker safety enforcement, including by enacting an emergency standard and ramping up penalties on violators. Biden's campaign also pledged to double the number of OSHA investigators to enforce the law and existing standards.
** Why Not - 2024
- [[https://www.theguardian.com/commentisfree/2024/nov/06/trump-wins-election-consequences-despair-america][the guardian]]
- promised mass deportations that will ruin lives and sunder families
- threatened to dismantle ACA and appoint anti-vac conspiracy theorist Robert F Kennedy  Jr to a position of authority on public health; pledged vast cuts to social security and medicare; promised persecution of dissidents and violent suppression of political enemies
- his vulgarity, corruption, pettiness, narcissism and bigotry have been rewarded, at our expense; once again, the nation will be plunged into chaos as his vanity, greed, incompetence and anger take precedence over the national interest; once again, a violently and grossly misogynist man has been elevated to a position of superlative power over a flawed but competent, hardworking woman
- Does America deserve Trump? In the years since he rose to power, one theory posits that he is merely the manifestation of the nation’s unexorcised demons – a vestige of the racism that allowed this country to build its economy off the backs of the enslaved, of the casual relationship to violence that allowed it to build its territory and its global hegemony through violent conquest and coercion, of the grubby love of money and shameless disregard for principle that have always motivated our rapacious economy. In this version of the story, Trump is not merely a morbid symptom, but something like America’s comeuppance, a punishment for our sins. Living under his rule takes on the grim appropriateness of one of those ironic punishments in the underworlds of classical mythology, or in the hell of Dante’s Inferno. It is a feature of this horror that those who suffer most under his rule are usually those who are least culpable for these trespasses. Because we never really atoned – not for slavery, not for empire, not for the slaughter and dispossession of Indigenous Americans or the wars on and exploitation of foreign countries – this is what we now must endure: a figure who brings these cruelties home and who mocks our self-flattering delusion that we ever were, ever could have been, anything else.
- [[https://www.theatlantic.com/politics/archive/2024/11/trump-wins-second-term-presidency/680546/?utm_medium=cr&utm_source=email&utm_campaign=11_06_2024_election2024_post_election_roundup_prospects_large&utm_term=Prospects][The Atlantic - Frum]]
- a country where millions of our fellow citizens voted for a president who knowingly promotes hatred and division; who lies—blatantly, shamelessly—every time he appears in public; who plotted to overturn an election in 2020 and, had he not won, was planning to try again in 2024.
- [[https://www.theatlantic.com/politics/archive/2024/11/why-trump-won/680555/?utm_medium=cr&utm_source=email&utm_campaign=11_06_2024_election2024_post_election_roundup_prospects_large&utm_term=Prospects][the atlantic]] - Throughout the campaign, Trump told voters that President Joe Biden, Vice President Kamala Harris, and undocumented immigrants were responsible for inflation, and that he would fix the problem. His proposals were often incoherent and nonsensical. For example, Trump promised to both whip inflation and also institute enormous tariffs, a combination nearly all economists agree is impossible. The mass deportation that Trump has promised would also likely drive up prices, rather than soothing the economy. But in a country where roughly three-quarters of Americans feel that things are on the wrong track, a pledge to fix things was potent.
- People feel that they don't have a meaningful say in how they're governed; people feel that the moral fabric of community has been unraveling; no sense of belonging, pride, solidarity (bowling alone); grievances of working people who feel elites look down on them; deepening inequality; for decades, neoliberal market-friendly globalization project leaving stagnant wages and outsourced jobs; if you're struggling, your failure is your fault; reversal of dem + repub, where the dems used to be the party of the working people -- dems emphasized market+meritocratic triumphalism; widening inequality + stalled mobility;
- If Trump were elected and decided to make Project 2025 a reality, his administration would take an existing piece of bureaucratic infrastructure, strip it of many of those who can check its power, and then wield that power to ideological ends and against their political enemies.
- And that prospect alarms me as much as the idea of putting a man who uncontrollably blurts out vulgarities in charge of our nukes. - Paul Krugman
* References
From: [[https://www.politico.com/news/magazine/2021/01/18/trump-presidency-administration-biggest-impact-policy-analysis-451479][Politico]]
